# Configuration for mergeable - https://github.com/mergeability/mergeable

defaults:
  checks_failure_payload: &checks_failure_payload
    title: 'Mergeable Run have been Completed!'
    summary: |
      ### Status: {{toUpperCase validationStatus}}
          Here are some stats of the run:
          {{validationCount}} validations were ran.
          {{passCount}} PASSED
          {{failCount}} FAILED
    text: "{{#each validationSuites}}\n
          #### {{{statusIcon status}}} Validator: {{toUpperCase name}}\n
          {{#each validations }} * {{{statusIcon status}}} ***{{{ description }}}***\n
                  Input : {{{details.input}}}\n
                  Settings : {{{displaySettings details.settings}}}\n
                  {{/each}}\n
          {{/each}}"

version: 2
mergeable:
  - when: pull_request.*, pull_request_review.*
    name: 'Validate Pull Request Description'
    validate:
      - do: description
        no_empty:
          enabled: true
    fail:
      - do: checks
        status: 'failure'
        payload: *checks_failure_payload
      - do: comment
        payload:
          body: 'Description is necessary and should not be empty. Kindly provide details with **what** was changed, **why** it was changed, and **how** it was changed.'
  - when: pull_request.*, pull_request_review.*
    name: 'Validate Pull Request Title'
    validate:
      - do: title
        no_empty:
          enabled: true
    fail:
      - do: checks
        status: 'failure'
        payload: *checks_failure_payload
      - do: comment
        payload:
          body: 'Title is necessary and should not be empty.'
  - when: pull_request.*, pull_request_review.*
    name: 'Validate Pull Request Size'
    validate:
      - do: size
        ignore:
          - '*.lock'
          - '*-lock.json'
        lines:
          max:
            count: 500
    fail:
      - do: checks
        status: 'failure'
        payload: *checks_failure_payload
      - do: comment
        payload:
          body: 'Lines of code have too many changes. It should be under 500 lines of addtions and deletions.'
  - when: pull_request.*, pull_request_review.*
    name: 'Validate Pull Request has one or more assignees'
    validate:
      - do: assignee
        min:
          count: 1
    fail:
      - do: checks
        status: 'failure'
        payload: *checks_failure_payload
      - do: comment
        payload:
          body: 'One or more assignees are required. Kindly add one or more assignees for this pull request.'
  - when: pull_request.*, pull_request_review.*
    name: 'Ensure Pull Request has been approved'
    filter:
      - do: author
        must_exclude:
          regex: 'tenshiAMD'
    validate:
      - do: approvals
        min:
          count: 1
  - when: pull_request.*, pull_request_review.*
    name: 'Restrict Pull Request as Work in Progress'
    validate:
      - do: label
        must_exclude:
          regex: 'wip'
      - do: title
        must_exclude:
          regex: ^\[WIP\]
  - when: pull_request.*, pull_request_review.*
    name: 'Validate Pull Request Head Ref'
    validate:
      - do: headRef
        must_include:
          regex: '^(feature|hotfix)\/.+$'
          message: |
            Your pull request does not adhere to the branch naming convention described <a href="https://datasift.github.io/gitflow/IntroducingGitFlow.html">here</a>.
#   - when: pull_request.*, pull_request_review.*
#     name: 'Validate Pull Request must not be a draft'
#     validate:
#       - do: payload
#         pull_request:
#           draft:
#             boolean:
#               match: false
