name: Run lints

on:
  pull_request:
    branches:
      - master

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      -
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      -
        uses: actions/setup-node@v3
        with:
          node-version: 16
      -
        run: npm install -g yaml-lint
      -
        name: Run yaml linter
        run: yamllint "**/*.(yaml|yml)"
