name: Update copyright year(s) in license file

on:
  schedule:
    - cron: "0 0 * * 0"
  workflow_call:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: FantasticFiasco/action-update-license-year@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          assignees: 'tenshiAMD'
          prBody: 'Update copyright year(s) in license file'
